### ISSUE TITLE
GitHub Action for manual releases

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu-flutter-community/musicpod#379]
@eboye hey I am taking another look and I would really like to have a githubaction to build the appimages for people who prefer manual downloads over store downloads

I am trying a github action but with the appimage-buidler action I miss some "app image receipe"

```yml
name: release linux appimage

on:
  push:
    branches:
      - main  


env:
  FLUTTER_VERSION: '3.16.x'

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: ${{env.FLUTTER_VERSION}}
      - run: sudo apt update
      - run: sudo apt install -y clang cmake curl libgtk-3-dev ninja-build pkg-config unzip libunwind-dev libgstreamer-plugins-base1.0-dev libgstreamer1.0-dev libmpv-dev
      - run: flutter pub get
      - uses: AppImageCrafters/build-appimage@master
        with:
          recipe: "./appimage-demo-qt5/AppImageBuilder.yml"
        env:
          UPDATE_INFO: gh-releases-zsync|AppImageCrafters|appimage-demo-qt5|latest|*x86_64.AppImage.zsync
```
Can your bash script be used to create such a receipe?

_Originally posted by @Feichtmeier in https://github.com/ubuntu-flutter-community/musicpod/issues/257#issuecomment-1866325051_

**Comment by siljva** [comment]
I can look into it

In the meantime, I think this could be the solution

https://github.com/AppImageCrafters/appimage-builder-flutter-example/blob/main/AppImageBuilder.yml#L4-L7

Those few lines are what the shell script should be implemented (changed).

**Comment by eboye** [comment]
Sorry, I've posted with my corporate account :D

I can look into it

In the meantime, I think this could be the solution

https://github.com/AppImageCrafters/appimage-builder-flutter-example/blob/main/AppImageBuilder.yml#L4-L7

Those few lines are what the shell script should be implemented (changed).

Here's the PR

https://github.com/ubuntu-flutter-community/musicpod/pull/393

**Comment by eboye** [comment]
And btw, I think it should be hooked to releases which there is none in this repo.

**Comment by Feichtmeier** [comment]
Hey 👋
The action works but it after the ran the app image is gone
Any idea how to connect this action to the releases?

**Comment by eboye** [comment]
```yaml
name: AppImage Release

on:
  push:
    branches: [ main ]

env:
  FLUTTER_VERSION: '3.16.x'

jobs:
  build-appimage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: ${{env.FLUTTER_VERSION}}
      - run: sudo apt update
      - run: sudo apt install -y clang cmake curl libgtk-3-dev ninja-build pkg-config unzip libunwind-dev libgstreamer-plugins-base1.0-dev libgstreamer1.0-dev libmpv-dev
      - run: flutter --disable-analytics
      - run: flutter pub get
      - run: flutter build linux --release
      - uses: AppImageCrafters/build-appimage@master
        with:
          recipe: "./AppImageBuilder.yml"
        env:
          UPLOAD_INFO: gh-releases-v2|ubuntu-flutter-community|musicpod|latest|*x86_64.AppImage
      - name: Create GitHub Release
        uses: appleboy/github-release@master
        with:
          tag_name: '${{ github.ref_name }}'
          token: ${{ secrets.GITHUB_TOKEN }}
```
I think these last 5 lines should do the trick. I think I made I typo for UPDATE_INFO in the first and UPLOAD_INFO should be correct.

You can try this, but I'll check it out when I get some spare time. This is out of head (and some other actions I've made).
